# Generated by Django 5.0.6 on 2024-07-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitlyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordance',
            name='short_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
